@startuml classes
set namespaceSeparator none
class "AssetsCommand" as commands.assets.AssetsCommand {
  assets_collector
  execute() -> None
}
class "BundleCommand" as commands.bundle.BundleCommand {
  assets_collector
  base : str
  kernel_builder
  package_type : Iterable[EnumPackageType]
  build_kernel(clean_only: Optional[bool]) -> None
  collect_assets() -> None
  conan_options(json_file: str) -> dict
  conan_package(options: tuple[str, ...], reference: str) -> None
  conan_sources() -> None
  conan_upload(reference: str) -> None
  execute() -> None
}
class "KernelCommand" as commands.kernel.KernelCommand {
  kernel_builder
  execute() -> None
}
@enduml
